[project]
name = "ollama-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.8.2",
    "ollama>=0.5.2",
    "streamlit>=1.48.0",
]
